settings:
  title: 'Status Page'
  url: 'https://status.turazlab.com' # used for Slack messages
  logo: turaz-nobg.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-turazlab-com
    name: turazlab.com
    description: 'Just another blog updated once a year'
    url: 'https://www.turazlab.com/'
    method: GET
    expectStatus: 200
  - id: www-turaz-net
    name: turaz.net
    description: 'Placeholder of my first website'
    url: 'https://www.turaz.net/'
    method: GET
    expectStatus: 200
